# basic options
title: COVID-19 Detection in CT scan images
author: Sumit Pandey 
email: sumit.ai.sci@gmail.com
github_username:  Sumit-ai

description: After watching this video, close the first issue in your repository.
video: https://youtube.com/embed/w3jLJU7DT5E

# Build settings
markdown: kramdown
theme: minima
